#
# Makefile for Heterogenous System Architecture support for AMD Radeon devices
#

obj-y                += virtio_kfd.o virtio_kfd_topology.o virtio_kfd_doorbell.o
CFLAGS_virtio_kfd.o = -O0
CFLAGS_virtio_kfd_topology.o = -O0
